<?php

return [
    'order' => 'required',
        'order.id' => 'required|alpha_dash|min:1|max:30',
        'order.amount' => 'required|numeric|digits_between:1,14',
        'order.currency' => 'sometimes|string|size:3',
        'order.description' => 'required|string|min:1|max:127',
        'order.timeout' => 'sometimes|numeric|digits_between:1,8',
        'order.itemAmount' => 'sometimes|numeric|digits_between:1,14',
        'order.localTaxRegistrationId' => 'sometimes|string|min:1|max:25',
        'order.merchantCategoryCode' => 'sometimes|string|size:4',
        'order.surchargeAmount' => 'sometimes|string|min:1|max:14',
        'order.item' => 'sometimes|array',
            'order.item.*.brand' => 'sometimes|required_with:order.item|string|min:1|max:127',
            'order.item.*.category' => 'required_with:order.item|string|min:1|max:127',
            'order.item.*.description' => 'required_with:order.item|string|min:1|max:127',
            'order.item.*.industryCategory' => 'sometimes|required_with:order.item|string|min:1|max:127',
            'order.item.*.name' => 'required_with:order.item|string|min:1|max:127',
            'order.item.*.quantity' => 'required_with:order.item|numeric|digits_between:1,3',
            'order.item.*.sku' => 'sometimes|required_with:order.item|string|min:1|max:127',
            'order.item.*.unitDiscountAmount' => 'sometimes|required_with:order.item|numeric|digits_between:1,14',
            'order.item.*.unitOfMeasure' => 'sometimes|required_with:order.item|string|min:1|max:10',
            'order.item.*.unitPrice' => 'required_with:order.item|numeric|digits_between:1,14',
            'order.item.*.unitTaxAmount' => 'sometimes|required_with:order.item|numeric|digits_between:1,14',
            'order.item.*.subMerchantId' => 'sometimes|required_with:order.item|string|min:1|max:127',
            'order.item.*.ServiceProvider' => 'sometimes|required_with:order.item|object',
                'order.item.*.ServiceProvider.id' => 'required_with:order.item.*.ServiceProvider|string|min:1|max:8',
                'order.item.*.ServiceProvider.type' => 'required_with:order.item.*.ServiceProvider|string|min:1|max:30',
                'order.item.*.ServiceProvider.customerId' => 'required_with:order.item.*.ServiceProvider|string|min:1|max:30',
            'order.item.*.url' => 'required_with:order.item|string|min:1|max:320',
            'order.item.*.imageUrl' => 'required_with:order.item|string|min:1|max:320',
        'order.transactionFiltering' => 'sometimes',
            'order.transactionFiltering.accepted' => 'sometimes',
            'order.transactionFiltering.rejected' => 'sometimes',
            'order.transactionFiltering.point' => 'sometimes',
                'order.transactionFiltering.point.last4' => 'sometimes|string|min:1|max:100',
                'order.transactionFiltering.point.ownedPoints' => 'sometimes|numeric|digits_between:1,14',
                'order.transactionFiltering.point.rule' => 'sometimes|array|min:1|max:100',
                    'order.transactionFiltering.point.rule.*.cardBin' => 'sometimes|numeric|digits:6',
                    'order.transactionFiltering.point.rule.*.pointToldr' => 'sometimes|string|min:1|max:14',
                    'order.transactionFiltering.point.rule.*.min' => 'sometimes',
                        'order.transactionFiltering.point.rule.*.min.amount' => 'sometimes|string|min:1|max:14',
                    'order.transactionFiltering.point.rule.*.max' => 'sometimes',
                        'order.transactionFiltering.point.rule.*.max.amount' => 'sometimes|string|min:1|max:14',
                        'order.transactionFiltering.point.rule.*.max.disc' => 'sometimes|string|min:1|max:3',

    'customer' => 'required',
        'customer.id' => 'required|string|min:1|max:320',
        'customer.email' => 'required|email|min:1|max:320',
        'customer.firstName' => 'required|string|min:1|max:50',
        'customer.lastName' => 'required|string|min:1|max:50',
        'customer.mobilePhone' => 'required|string|min:1|max:20',
        'customer.phone' => 'sometimes|string|min:1|max:15',
        'customer.taxRegistrationId' => 'sometimes|string|min:1|max:30',
        'customer.account' => 'sometimes',
            'customer.account.id' => 'sometimes|string|min:1|max:40',


    'url' => 'required',
        'url.backUrl' => 'required',
    'billing' => 'nullable',
    'shipping' => 'nullable',
    'meta' => 'nullable',
    'card' => 'nullable',
    'reccuring' => 'nullable',
    'sourceOfFunds' => 'required',
    'device' => 'nullable',
];
