<?php

return [
    'order' => 'required|array',
    'order.id' => 'required|alpha_dash',
    'order.amount' => 'required|numeric',
    'order.currency' => 'sometimes|string',
    'order.description' => 'required|string',
    'order.timeout' => 'sometimes|numeric',
    'order.itemAmount' => 'sometimes|numeric',
    'order.localTaxRegistrationId' => 'sometimes|string',
    'order.merchantCategoryCode' => 'sometimes|string',
    'order.surchargeAmount' => 'sometimes|string',
    'order.item' => 'sometimes|array',
        'order.item.*.brand' => 'sometimes|required_with:order.item|string|min:1|max:127',
        'order.item.*.category' => 'required_with:order.item|string|min:1|max:127',
        'order.item.*.description' => 'required_with:order.item|string|min:1|max:127',
        'order.item.*.industryCategory' => 'sometimes|required_with:order.item|string|min:1|max:127',
        'order.item.*.name' => 'required_with:order.item|string|min:1|max:127',
        'order.item.*.quantity' => 'required_with:order.item|numeric|digits_between:1,3',
        'order.item.*.sku' => 'sometimes|required_with:order.item|string|min:1|max:127',
        'order.item.*.unitDiscountAmount' => 'sometimes|required_with:order.item|numeric|digits_between:1,14',
        'order.item.*.unitOfMeasure' => 'sometimes|required_with:order.item|string|min:1|max:10',
        'order.item.*.unitPrice' => 'required_with:order.item|numeric|digits_between:1,14',
        'order.item.*.unitTaxAmount' => 'sometimes|required_with:order.item|numeric|digits_between:1,14',
        'order.item.*.subMerchantId' => 'sometimes|required_with:order.item|string|min:1|max:127',
        'order.item.*.ServiceProvider' => 'sometimes|required_with:order.item|object',
            'order.item.*.ServiceProvider.id' => 'required_with:order.item.*.ServiceProvider|string|min:1|max:8',
            'order.item.*.ServiceProvider.type' => 'required_with:order.item.*.ServiceProvider|string|min:1|max:30',
            'order.item.*.ServiceProvider.customerId' => 'required_with:order.item.*.ServiceProvider|string|min:1|max:30',
        'order.item.*.url' => 'required_with:order.item|string|min:1|max:320',
        'order.item.*.imageUrl' => 'required_with:order.item|string|min:1|max:320',

    'customer' => 'required',
    'url' => 'required',
    'billing' => 'nullable',
    'shipping' => 'nullable',
    'meta' => 'nullable',
    'card' => 'nullable',
    'reccuring' => 'nullable',
    'sourceOfFunds' => 'required',
    'device' => 'nullable',
];
